services:
  ocr-service:
    build:
      args:
        OCR_PADDLE_PACKAGE: paddlepaddle-gpu==3.3.0
        OCR_PADDLE_INDEX: https://www.paddlepaddle.org.cn/packages/stable/cu126/
    environment:
      OCR_DEVICE: gpu:0
      OCR_ENABLE_HPI: "true"
    gpus: all
